### ISSUE TITLE
(docs) update README

### ISSUE THREAD

**Issue by ghost** [ARolek/ase#12]
While working on the refactor for this library, I have collected a handful of observations that helped me understand the ASE specification as detailed by [Selapa's ASE Specification](http://www.selapa.net/swatches/colors/fileformats.php#adobe_ase).

I think the README could benefit users by explaining what that specification is in clearer terms, how the `ase.Decode` function works at a high-level, and the meaning of each key-value pair in the output struct.

**Comment by ARolek** [comment]
While I agree, this is not a top priority. Understanding the spec is important for the engineer creating the package, but not as important to detail for the user of the package.

**Comment by ghost** [comment]
@ARolek Got it. I will close it in the meantime and reopen it if it ever becomes a higher priority.
