### ISSUE TITLE
(discuss) Better Logging

### ISSUE THREAD

**Issue by ghost** [ARolek/ase#3]
At the moment, the example code showcasing the ASE decoder writes the output to `stdout`.

What constitutes "better logging" in this context: file output options, output formatting, or something else? @ARolek

**Comment by ARolek** [comment]
@francismakes right now there's a lot of debug logs when you run the package. We should either remove them, comment them out, or make them part of a debug mode. I think removing them makes the most sense.

**Comment by ghost** [comment]
@ARolek I agree with removing them. We can always check back a commit if we decide to make them a part of debug mode or want to restore them. I'll be pushing up an experimental branch identifying where those initial logs happen in just a moment.

**Comment by ghost** [comment]
@ARolek Would appreciate a code review before merging, please and thanks!

**Comment by ARolek** [comment]
@francismakes looked fine. Those were all debug messages for me. They just needed to be cleaned out.

**Comment by ghost** [comment]
@ARolek Perfect, thanks!
